# Generated by Django 4.2.5 on 2023-10-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(default=None, max_length=225),
        ),
    ]
