# Generated by Django 4.2.5 on 2023-10-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_bio_user_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
