# Generated by Django 4.2.5 on 2023-10-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
