# Generated by Django 4.2.5 on 2023-10-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='sender',
            new_name='user',
        ),
    ]
