# Generated by Django 4.2.5 on 2023-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='recieving_user_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
