# Generated by Django 4.2.5 on 2023-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usermessage_recieving_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=225)),
                ('message_content', models.CharField(max_length=5000)),
                ('reciepients', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
