# Generated by Django 4.2.5 on 2023-10-13 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_emailmessage_delete_emailconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message_content', models.TextField()),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
