# Generated by Django 4.2.5 on 2023-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_taskinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='location',
            field=models.CharField(default=None, max_length=225),
        ),
    ]
