# Generated by Django 4.2.5 on 2023-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_taskinfo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='location',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
